task/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from todo import settings
app_name="task"

urlpatterns = [
    path('', views.taskdetails,name="task_details"),
    path('delete/<int:slug>/', views.deletetask,name="delete"),
    path('update/<int:slug>/', views.update,name="update"),
    
    
    path('create-view/', views.TodoCreateView.as_view(),name="create_view"),
    path('list-view/', views.TodoListView.as_view(),name="list_view"),
    path('detail-view/<int:pk>/', views.TodoDetailView.as_view(),name="detail_view"),
    path('update-view/<int:pk>/', views.TodoUpdateView.as_view(),name="update_view"),
    path('delete-view/<int:pk>/', views.TodoDeleteView.as_view(),name="delete_view"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
]

task/models.py
from django.db import models

# Create your models here.
class TaskModel(models.Model):
    task=models.CharField( max_length=50)
    priority=models.IntegerField(default=0)
    date=models.DateField()

task/forms.py
from django import forms
from .models import TaskModel

class TaskForm(forms.ModelForm):
    class Meta():
        model=TaskModel
        fields='__all__'
        

task/views.py
from django.shortcuts import render,redirect
from .models import TaskModel
from django.contrib import messages
from .forms import TaskForm
from django.views.generic import DetailView,UpdateView,ListView,DeleteView,CreateView
from django.urls import reverse,reverse_lazy

# Create your views here.
def taskdetails(request):
    task_list=TaskModel.objects.all().order_by('priority')
    if request.method=="POST":
        task=request.POST.get('task',None)
        priority=request.POST.get('priority',None)
        date=request.POST.get('date',None)
        if task and priority:
            add_task=TaskModel(task=task,priority=priority,date=date)
            add_task.save()
            return redirect("/")
        else:
            messages.error(request,'Pls enter valid data')
    return render(request,"index.html",{'task_list':task_list})

def deletetask(request,slug):
    TaskModel.objects.filter(id=slug).delete()
    return redirect('/')

def update(request,slug):
    update_task=TaskModel.objects.filter(id=slug).first()
    if request.method=="POST":
        print("aaaaaa")
        form=TaskForm(request.POST or None,instance=update_task)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form=TaskForm(instance=update_task)
    return render(request,"update.html",{'form':form})


# ==========================================================
class TodoCreateView(CreateView):
    model = TaskModel
    form_class = TaskForm
    template_name = 'create_view.html'
    success_url = reverse_lazy('task:create_view')

class TodoListView(ListView):
    context={}
    model=TaskModel
    template_name = "list_view.html"
    context_object_name ='task_list'
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['task_list']='task_list'
    #     return context
    
class TodoDetailView(DetailView):
    model=TaskModel
    template_name="details.html"
    context_object_name='task_list'
    
class TodoUpdateView(UpdateView):
    model=TaskModel
    form_class = TaskForm
    template_name="update_view.html"
    # context_object_name='task_list'
    # fields=('task','priority','date')

    def get_success_url(self):
        return reverse_lazy('task:detail_view', kwargs={'pk': self.object.id})
    
class TodoDeleteView(DeleteView):
    model=TaskModel
    template_name="delete.html"
    success_url=reverse_lazy('task:list_view')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TODO</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>

<div class="container-fluid">
  <div class="banner">
      <div class="row">
          <div class="col-md-12">
              <div class="banner-text">
                  <h1>TODO</h1>    
              </div>
          </div>
      </div>
  </div>
</div>
{% block body %}

{% endblock  %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>
</html>

templates/create_view.html
{% extends 'base.html' %}
{% block body %}

<div class="container w-50" >
    <form method="post" class="p-4 shadow-lg">
        {% csrf_token %}
        
        <div class="form-group">
            <label >Task Name</label>
            <input type="text" class="form-control" name="task" placeholder="Enter Task">
        </div>
        <div class="form-group">
            <label >Priority</label>
            <input type="number" class="form-control" name="priority" placeholder="Enter Priority">
        </div>
        <div class="form-group">
            <label >Date</label>
            <input type="date" class="form-control" name="date" placeholder="Enter Date">
        </div>
        <div class="row">
            <div class="col text-left">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            <div class="col text-right">
              <a class="btn btn-primary" href="{% url 'task:list_view' %}">List Items</a>
            </div>
        </div>
    </form>
</div>

{% endblock  %}

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container p-5 shadow-lg" style="width: 50%;">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to Delete??</p>
        <a type="submit" class="btn btn-secondary" href="javascript:window.history.back()">Cancel</a>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </form>
</div>

{% endblock  %}

templates/details.html
{% extends 'base.html' %}
{% block body %}

<div class="container" >
    <div class="row">
        <div class="col-md-4">
            {% if task_list %}
            <h4>Task to be Completed</h4>
            {% endif %}
            <div class="card mb-4">
                <div class="card-body shadow">
                    <h5 class="card-title">{{task_list.task}}</h5>
                    <h5 class="card-title">{{task_list.priority}}</h5>
                    <h5 class="card-title">{{task_list.date}}</h5>
                    <a type="button" class="btn btn-danger" href="{% url 'task:delete_view' task_list.id %}">Done</a>
                    <a type="button" class="btn btn-success" href="{% url 'task:update_view' task_list.id %}">Update</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container" >
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-4 shadow-lg">
                {% csrf_token %}
                
                <div class="form-group">
                  <label >Task Name</label>
                  <input type="text" class="form-control" name="task" placeholder="Enter Task">
                </div>
                <div class="form-group">
                  <label >Priority</label>
                  <input type="number" class="form-control" name="priority" placeholder="Enter Priority">
                </div>
                <div class="form-group">
                  <label >Date</label>
                  <input type="date" class="form-control" name="date" placeholder="Enter Date">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-6 pl-md-5">
            {% if task_list %}
            <h4>Task to be Completed</h4>
            {% endif %}
            {% for i in task_list %}
                <div class="card mb-4">
                    <div class="card-body shadow">
                        <h5 class="card-title">{{i.task}}</h5>
                        <h5 class="card-title">{{i.priority}}</h5>
                        <h5 class="card-title">{{i.date}}</h5>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter{{i.id}}">Done</button>
                        <a type="button" class="btn btn-success" href="{% url 'task:update' i.id %}">Update</a>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModalCenter{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Are you sure you want to Delete "{{i.task}}" task ??</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'task:delete' i.id %}'">Confirm</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock  %}

templates/list_view.html
{% extends 'base.html' %}
{% block body %}

<div class="container w-50" >
    {% if task_list %}
    <span class="h3">List of all Tasks</span>
    <a type="button" class="btn btn-primary mb-2 ml-3" href="{% url 'task:create_view' %}">Add</a>
    {% endif %}
    {% for i in task_list %}
        <div class="card mb-4">
            <div class="card-body shadow">
                <h5 class="card-title">{{i.task}}</h5>
                <h5 class="card-title">{{i.priority}}</h5>
                <h5 class="card-title">{{i.date}}</h5>
                <a type="button" class="btn btn-success" href="{% url 'task:detail_view' i.id %}">Details</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock  %}

templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container p-5 shadow-lg" style="width: 50%;">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
</div>

{% endblock  %}

templates/update_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container p-5 shadow-lg" style="width: 50%;">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
</div>

{% endblock  %}